### ISSUE TITLE
Lesson data is downloaded two times upon first load

### ISSUE THREAD

**Issue by skyzh** [SJTU-Plus/course-plus#24]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/4198311/89969276-8f88ed80-dc88-11ea-8931-739f650786b4.png">

**Comment by danyang685** [comment]
They are triigered by `onSelectedYearChanged` and `onSelectedSemesterChanged` separately.
I add the 100ms cooling time in `updateSrcData`, it will work better now.

https://github.com/SJTU-Plus/course-plus/pull/32
