### ISSUE TITLE
本研互选课程同步问题

### ISSUE THREAD

**Issue by AlanHN** [SJTU-Plus/course-plus#97]
本研互选课程中的研究生专业基础课在2022-2-14被放出，而网站上的数据库同步时间为2021-12-28，缺少一部分专业基础课信息，希望能重新同步一下，详情可见[关于2021-2022学年春季学期本科生研究生课程互选的通知](http://www.jwc.sjtu.edu.cn/info/1222/11427.htm)
（btw,我点击同步数据后，会跳回到主页面（/browse）但是无任何选课数据，不确定是不是由于信息不同步导致的

**Comment by skyzh** [comment]
Hi, 最近学校接口出现了一些问题，导致数据拉不下来。我们在修复这个问题。

**Comment by skyzh** [comment]
我们已经同步了最新数据 https://github.com/SJTU-Plus/course-plus-data/pull/30 ，稍后更新到网站。
